language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - docker pull bit3/jsass-test-centos5
  - docker pull bit3/jsass-test-centos6
  - docker pull bit3/jsass-test-centos7
  - docker pull bit3/jsass-test-ubuntu12.04
  - docker pull bit3/jsass-test-ubuntu14.04

script:
  - gradle check
